version: '3'
services:
  app:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - mongo
    environment:
      - DATABASE=mongodb://mongo:27017/idurar-erp-crm
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dave
      - MONGO_INITDB_ROOT_PASSWORD=password123
